name: API Deployment on AKS

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Configure kubectl
      #   run: az aks get-credentials --resource-group "NewLook-Test" --name "Newlook-aks"

      # - uses: Azure/docker-login@v1
      #   with:
      #     login-server: cloudlifeacr.azurecr.io
      #     username: ${{ secrets.ACR_USERNAME }}
      #     password: ${{ secrets.ACR_PASSWORD }}
      
      # - run: |
      #     docker build -t newlookapi.azurecr.io/NewlookApi:${GITHUB_RUN_NUMBER} .
      #     docker login myacr.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
      #     docker push myacr.azurecr.io/myapp:${GITHUB_RUN_NUMBER}
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_SERVICE_PRINCIPAL_ID }}","clientSecret":"${{ secrets.AZURE_SERVICE_PRINCIPAL_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
        
      # - name: Run kubectl command
      #   run: kubectl get pods
